FROM node:20-alpine AS buildstage

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY tsconfig.json ./
COPY src/ ./src/

RUN npm run build

RUN adduser -S visiteur
USER visiteur

EXPOSE 3000





FROM node:20-alpine
WORKDIR /app
COPY --from=buildstage /app/build/index.js .

CMD ["node", "index.js"]